name: deploy-pages

on:
  schedule:
    # Mon–Fri at 22:15 UTC (adjust as you like)
    - cron: "15 22 * * 1-5"
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      # ✅ Write .env only if the secret exists (no YAML if:, use shell + env)
      - name: Write .env from secret (optional)
        run: |
          if [ -n "${NEWSAPI_KEY}" ]; then
            echo "NEWSAPI_KEY=${NEWSAPI_KEY}" > .env
            echo "Wrote .env with NEWSAPI_KEY"
          else
            echo "No NEWSAPI_KEY secret set; continuing without news sentiment."
          fi
        env:
          NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}

      - name: Run pipeline (SELL/BUY + positions)
        run: |
          python -m src.pipeline || python src/pipeline.py

      - name: Build static HTML report (index + archive)
        run: |
          python src/report/make_html.py
          mkdir -p _site
          cp -r reports/* _site/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4


